// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfJgyumvSevAflQj0MZtIgjK2xjsPyZ5k',
    appId: '1:975936970894:web:639f658fcc5c396cd229df',
    messagingSenderId: '975936970894',
    projectId: 'flutter-banking-app-2026',
    authDomain: 'flutter-banking-app-2026.firebaseapp.com',
    storageBucket: 'flutter-banking-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkM15AsCE22XsxiXZGhB1QMPbVyIU7zM',
    appId: '1:975936970894:android:dd1a1a0eaab66994d229df',
    messagingSenderId: '975936970894',
    projectId: 'flutter-banking-app-2026',
    storageBucket: 'flutter-banking-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpNm661UuzQo5e76tnv5UxSJRVA6xkEMw',
    appId: '1:975936970894:ios:9ab4953ad841a71bd229df',
    messagingSenderId: '975936970894',
    projectId: 'flutter-banking-app-2026',
    storageBucket: 'flutter-banking-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpNm661UuzQo5e76tnv5UxSJRVA6xkEMw',
    appId: '1:975936970894:ios:9ab4953ad841a71bd229df',
    messagingSenderId: '975936970894',
    projectId: 'flutter-banking-app-2026',
    storageBucket: 'flutter-banking-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfJgyumvSevAflQj0MZtIgjK2xjsPyZ5k',
    appId: '1:975936970894:web:62f7b9e097cb915fd229df',
    messagingSenderId: '975936970894',
    projectId: 'flutter-banking-app-2026',
    authDomain: 'flutter-banking-app-2026.firebaseapp.com',
    storageBucket: 'flutter-banking-app-2026.firebasestorage.app',
  );
}
